### ISSUE TITLE
[仕様検討] UI 仕様

### ISSUE THREAD

**Issue by ymatsukawa** [buildBase/ez_report#3]
### [customer:ymatsukawa]

業務仕様を踏まえた上で、画面上どういう項目を設置した方が良いかを考えて形式化する。

* 形式化の方法はお任せ。keynote でプロトタイプするもよし、紙に書いてスキャンするもよし。

**Comment by TAKEC5** [comment]
![default](https://cloud.githubusercontent.com/assets/13291137/26529610/f0e9e5ba-43fd-11e7-9c52-40614763b4fe.png)

**Comment by TAKEC5** [comment]
@ymatsukawa 
keynoteで作成してみました。

洗い出しの際は、日次報告業務、自動テスト、朝会などがありましたが、現在はまとめて１時間とみて報告から除外しているため、入力フォームからも除外させていただきました。

**Comment by TAKEC5** [comment]
項目を入力し、確認を押す事で次の画面に移行しツリー型にフォーマットされたものを最終確認することができます。
またその画面の送信ボタンを押す事で、slackチャンネルに送信されます。

**Comment by ymatsukawa** [comment]
@TAKEC5 

[customer:ymatsukawa]
2 点

まず一つ目は
あえての質問ですが、、プルダウンには時間が入ると思って良いでしょうか？

二つ目ですが
三つ目のボックスの左下にある + を押下すると、どういった挙動になりますか？
[タスク業務] というボックスが一つ増えると推測していますが、そのように想定してよいでしょうか。
+ でボックスを増やしたら - でボックスを減らす動線も必要じゃないかと思っていたり。

[dev:ymatsukawa]
アウトプットは良かったと思います。
ここでは求められなかったのですが、画面遷移系の話は
文字だけでなく遷移図も付け加えると尚良いです。

画面遷移図とは、iOS の storyboard のような図を書き起こすようなイメージです。
[超ざっくり想定](https://koenig-media.raywenderlich.com/uploads/2012/11/Full-storyboard.png)

(今回は添付しなくて良いです)

**Comment by TAKEC5** [comment]
### 質問について
* プルダウンには時間が入ると思って良いか
  * ご認識の通り
* 三つ目のボックスの左下にある + を押下すると、どういった挙動になるか
  * 小タスクの枠が一つ増えます。また、枠左したの+ボタンを押すと大タスクが増えます
  * 「-」については漏れていました


* 遷移図について承知しました

**Comment by ymatsukawa** [comment]
@TAKEC5 
[customer:ymatsukawa]
次の UX 検討で - ボタンを付記するようお願いします。
UI 仕様については以上です。
